const services = [
  ["01", "computer", "Computer Repair", "Desktop and laptop troubleshooting, hardware support and performance help."],
  ["02", "business", "Business IT Support", "Practical support for home offices, professionals and small businesses."],
  ["03", "wifi", "Wi-Fi & Networking", "Wireless setup, network troubleshooting, printers and device connectivity."],
  ["04", "shield", "Virus Removal", "Virus and spyware removal plus safer-computing guidance."],
  ["05", "settings", "Computer Setup", "New computers, laptops, software, printers and internet setup."],
  ["06", "code", "Web Services", "Web design, development, hosting, domains and webmaster support."]
];

const benefits = [
  ["support", "One-stop support", "Sales, repair, setup and everyday technical support in one place."],
  ["location", "Local service", "Based in Markham and serving customers across Toronto and the GTA."],
  ["practical", "Practical solutions", "Clear help focused on getting your technology working again."],
  ["personal", "Personal service", "Support designed for households, home offices and small businesses."]
];

function ServiceIcon({ type }) {
  const common = { viewBox: "0 0 24 24", fill: "none", stroke: "currentColor", strokeWidth: "1.9", strokeLinecap: "round", strokeLinejoin: "round", "aria-hidden": "true" };
  if (type === "computer") return <svg {...common}><rect x="3" y="4" width="14" height="10" rx="2"/><path d="M6 18h7M9.5 14v4"/><path d="m16 12 4-4M18.5 6.5l1-1 2 2-1 1M15.5 12.5l-2.5 2.5"/></svg>;
  if (type === "business") return <svg {...common}><rect x="3" y="3" width="11" height="18" rx="2"/><path d="M6 7h2M10 7h1M6 11h2M10 11h1M6 15h2"/><circle cx="18" cy="16" r="3"/><path d="M18 11.5v1M18 19.5v1M13.5 16h1M21.5 16h1M14.8 12.8l.7.7M20.5 18.5l.7.7M21.2 12.8l-.7.7M15.5 18.5l-.7.7"/></svg>;
  if (type === "wifi") return <svg {...common}><path d="M5 9a10 10 0 0 1 14 0M8 12a6 6 0 0 1 8 0M10.7 15a2 2 0 0 1 2.6 0"/><rect x="4" y="17" width="16" height="4" rx="1.5"/><path d="M7 19h.01M10 19h.01"/></svg>;
  if (type === "shield") return <svg {...common}><path d="M12 3 19 6v5c0 4.6-2.9 8-7 10-4.1-2-7-5.4-7-10V6l7-3Z"/><path d="m8.8 12.1 2.1 2.1 4.4-4.7"/></svg>;
  if (type === "settings") return <svg {...common}><rect x="3" y="4" width="14" height="10" rx="2"/><path d="M7 18h6M10 14v4"/><circle cx="18" cy="16" r="2.5"/><path d="M18 12.2v1M18 18.8v1M14.2 16h1M20.8 16h1M15.3 13.3l.7.7M20 18l.7.7M20.7 13.3l-.7.7M16 18l-.7.7"/></svg>;
  return <svg {...common}><rect x="3" y="4" width="18" height="16" rx="2"/><path d="M3 8h18"/><path d="m9 12-2 2 2 2M15 12l2 2-2 2M13 11l-2 6"/></svg>;
}

function BenefitIcon({ type }) {
  const common = { viewBox: "0 0 24 24", fill: "none", stroke: "currentColor", strokeWidth: "1.9", strokeLinecap: "round", strokeLinejoin: "round", "aria-hidden": "true" };
  if (type === "support") return <svg {...common}><circle cx="12" cy="8" r="3"/><circle cx="6" cy="11" r="2"/><circle cx="18" cy="11" r="2"/><path d="M7 20v-1.5A4.5 4.5 0 0 1 11.5 14h1A4.5 4.5 0 0 1 17 18.5V20M2.5 19v-1a3 3 0 0 1 3-3M21.5 19v-1a3 3 0 0 0-3-3"/></svg>;
  if (type === "location") return <svg {...common}><path d="M12 21s6-5.3 6-11a6 6 0 1 0-12 0c0 5.7 6 11 6 11Z"/><circle cx="12" cy="10" r="2"/></svg>;
  if (type === "practical") return <svg {...common}><path d="M9 18h6M10 21h4"/><path d="M8.2 14.7A7 7 0 1 1 15.8 14.7C14.7 15.5 14 16.7 14 18h-4c0-1.3-.7-2.5-1.8-3.3Z"/><path d="M12 2V1M4.9 5l-.8-.8M19.1 5l.8-.8M3 12H2M22 12h-1"/></svg>;
  return <svg {...common}><path d="m8.5 12.5 2.2 2.2a2 2 0 0 0 2.8 0l2-2"/><path d="m3 11 4-4 3 3-4 4-3-3ZM21 11l-4-4-3 3 4 4 3-3Z"/><path d="m7 14 3 3a3 3 0 0 0 4 0l3-3"/></svg>;
}

function TestWhyIcon({ type }) {
  const common = { viewBox: "0 0 24 24", fill: "none", stroke: "currentColor", strokeWidth: "1.8", strokeLinecap: "round", strokeLinejoin: "round", "aria-hidden": "true" };
  if (type === "experienced") return <svg {...common}><path d="M7 11v9M7 11l3-7c.5-1.1 2-1 2.4.2L13 7h5a2 2 0 0 1 2 2l-1 8a3 3 0 0 1-3 3H7"/><path d="M3 11h4v9H3z"/></svg>;
  if (type === "friendly") return <svg {...common}><circle cx="9" cy="8" r="3"/><circle cx="16" cy="9" r="2.5"/><path d="M3 20v-2a5 5 0 0 1 5-5h2a5 5 0 0 1 5 5v2M15 14h1a5 5 0 0 1 5 5v1"/></svg>;
  if (type === "fast") return <svg {...common}><circle cx="12" cy="12" r="9"/><path d="M12 7v5l3 2"/></svg>;
  return <svg {...common}><path d="M12 21s6-5.3 6-11a6 6 0 1 0-12 0c0 5.7 6 11 6 11Z"/><circle cx="12" cy="10" r="2"/></svg>;
}

export default function Home() {
  return (
    <main>
      <style>{`
        .brandMark{overflow:hidden;background:linear-gradient(145deg,#f5f9ff,#eaf3ff);box-shadow:inset 0 0 0 1px rgba(17,105,219,.05)}
        .brandMark:before{width:23px!important;height:16px!important;top:8px!important;background:transparent!important;border:2px solid #1169db;border-radius:4px!important}.brandMark:after{width:17px!important;height:2px!important;top:27px!important;background:#1169db!important;border-radius:99px!important}.brandMark span{display:none!important}
        .servicesSection{padding-top:88px;padding-bottom:96px}.servicesSection .splitHead{margin-bottom:34px}.cards{gap:22px!important}.card{position:relative;min-height:232px!important;padding:24px 25px 23px!important;border-radius:18px!important;border:1px solid #e1e9f2!important;background:linear-gradient(180deg,#fff 0%,#fbfdff 100%)!important;box-shadow:0 8px 24px rgba(18,50,86,.045);overflow:hidden}.card:before{content:"";position:absolute;inset:0 auto 0 0;width:3px;background:#1169db;opacity:0;transition:.25s}.card:hover{transform:translateY(-4px)!important;box-shadow:0 18px 38px rgba(15,42,74,.10)!important;border-color:#cfe0f4!important}.card:hover:before{opacity:1}.cardTop{align-items:center!important}.serviceMeta{display:flex;align-items:center;gap:12px}.serviceIcon{width:54px;height:54px;border-radius:15px;display:grid;place-items:center;background:#edf5ff;color:#1169db;line-height:1;flex:0 0 54px}.serviceIcon svg{width:29px;height:29px;display:block}.cardNum{font-size:10px!important;letter-spacing:.14em!important;color:#7990aa!important}.cardArrow{width:31px!important;height:31px!important;font-size:13px;transition:.2s}.card:hover .cardArrow{background:#1169db;color:white;transform:translate(1px,-1px)}.card h3{font-size:21px!important;margin:18px 0 8px!important;line-height:1.2}.card p{font-size:14.5px;line-height:1.58!important;max-width:95%}.card a{margin-top:18px!important;padding-top:0!important;font-size:12.5px!important;display:inline-flex;gap:6px;align-items:center}.card a span{transition:.2s}.card:hover a span{transform:translateX(3px)}
        .whySection{padding-top:88px!important;padding-bottom:92px!important}.whySection .centered{margin-bottom:38px!important}.whyGrid{gap:18px!important}.whyGrid article{position:relative;min-height:220px;padding:24px!important;border:1px solid #dfe8f2!important;border-radius:18px!important;background:linear-gradient(180deg,#fff 0%,#fbfdff 100%)!important;box-shadow:0 8px 24px rgba(18,50,86,.045);transition:.25s;overflow:hidden}.benefitTop{display:flex;align-items:center;justify-content:space-between;gap:14px}.benefitIcon{width:48px;height:48px;border-radius:14px;display:grid;place-items:center;background:#edf5ff;color:#1169db;flex:0 0 48px}.benefitIcon svg{width:25px;height:25px;display:block}.benefitNum{font-size:10px!important;font-weight:900!important;letter-spacing:.14em!important;color:#8195aa!important}.whyGrid h3{font-size:19px!important;margin:22px 0 9px!important}.whyGrid p{font-size:14px;line-height:1.6!important;color:#66778c!important}
        .experimentalWhy{position:relative;overflow:hidden;background:linear-gradient(90deg,#f8fbff 0%,#f3f8fd 57%,#eef4f8 100%);border-top:1px solid #e4ecf5;border-bottom:1px solid #e4ecf5}.experimentalWhy .testWrap{width:min(1400px,94%);margin:auto;display:grid;grid-template-columns:1.55fr .85fr;min-height:430px}.testLeft{padding:48px 30px 44px 0}.testLabel{font-size:10px;letter-spacing:.18em;color:#7c8ca0;font-weight:800;margin-bottom:13px}.testLeft h2{font-size:44px;line-height:1.02;letter-spacing:-.04em;margin:0;color:#0d2443}.testSub{font-size:18px;color:#53667e;margin:8px 0 34px}.testBenefits{display:grid;grid-template-columns:repeat(4,1fr);gap:0;margin-top:24px}.testBenefit{padding:0 24px 0 0;min-height:156px}.testBenefit+.testBenefit{border-left:1px solid #d8e3ee;padding-left:28px}.testBenefitIcon{width:48px;height:48px;color:#1169db;margin-bottom:14px}.testBenefitIcon svg{width:100%;height:100%}.testBenefit h3{font-size:17px;margin:0 0 7px;color:#0d2443}.testBenefit p{font-size:14px;line-height:1.5;color:#53667e;margin:0}.testVisual{position:relative;min-height:430px;background:linear-gradient(135deg,#eaf2f8,#f9fbfd);overflow:hidden}.desk{position:absolute;left:0;right:0;bottom:0;height:112px;background:linear-gradient(#d9b58c,#c99f70)}.laptop{position:absolute;width:260px;height:170px;left:9%;bottom:94px;background:#0c1725;border-radius:10px 10px 4px 4px;transform:rotate(-5deg);box-shadow:0 18px 30px rgba(0,0,0,.22)}.laptopScreen{position:absolute;inset:11px;background:linear-gradient(145deg,#0e3f76,#0d2443);border-radius:4px;display:grid;grid-template-columns:1fr 1fr;gap:7px;padding:14px}.laptopScreen span{background:#155aa1;border-radius:4px}.laptop:after{content:"";position:absolute;width:300px;height:14px;background:#aeb8c3;left:-22px;bottom:-16px;border-radius:3px 3px 12px 12px}.plant{position:absolute;width:82px;height:82px;left:0;bottom:105px}.plant:before{content:"";position:absolute;width:55px;height:52px;background:#fff;bottom:0;left:13px;border-radius:7px 7px 13px 13px;box-shadow:0 6px 12px rgba(0,0,0,.08)}.plant:after{content:"✦✦✦";position:absolute;top:-11px;left:12px;color:#4b8e58;font-size:31px;letter-spacing:-9px;transform:rotate(-14deg)}.mug{position:absolute;right:9%;bottom:58px;width:95px;height:116px;background:#fff;border-radius:6px 6px 16px 16px;box-shadow:0 10px 24px rgba(0,0,0,.12);display:grid;place-items:center;text-align:center;font-weight:900;font-size:20px;line-height:.95;color:#0d2443}.mug:after{content:"";position:absolute;width:37px;height:46px;border:9px solid #fff;border-left:0;border-radius:0 28px 28px 0;right:-29px;top:27px}.possibility{position:absolute;right:7%;top:40px;font-family:cursive;font-size:26px;line-height:1.05;color:#0d2443;transform:rotate(-5deg)}.possibility:after{content:"";display:block;width:135px;height:3px;background:#1169db;margin:8px auto 0;transform:rotate(-4deg)}
        @media(max-width:980px){.cards{gap:18px!important}.card{min-height:220px!important}.whyGrid{gap:16px!important}.experimentalWhy .testWrap{grid-template-columns:1fr}.testLeft{padding-right:0}.testVisual{min-height:350px}.testBenefits{grid-template-columns:repeat(2,1fr);gap:24px}.testBenefit+.testBenefit{border-left:0;padding-left:0}}
        @media(max-width:640px){.servicesSection{padding-top:64px;padding-bottom:68px}.cards{gap:14px!important}.card{min-height:0!important;padding:21px!important}.card h3{margin-top:17px!important}.card p{max-width:100%}.serviceIcon{width:48px;height:48px;flex-basis:48px}.serviceIcon svg{width:25px;height:25px}.whySection{padding-top:64px!important;padding-bottom:68px!important}.whyGrid{gap:14px!important}.whyGrid article{min-height:0;padding:21px!important}.benefitIcon{width:44px;height:44px;flex-basis:44px}.benefitIcon svg{width:23px;height:23px}.experimentalWhy .testWrap{width:min(100% - 30px,1400px)}.testLeft{padding:38px 0 34px}.testLeft h2{font-size:34px}.testSub{font-size:16px}.testBenefits{grid-template-columns:1fr}.testBenefit{min-height:0;padding:18px 0;border-bottom:1px solid #d8e3ee}.testVisual{min-height:300px}.laptop{width:205px;height:135px;left:4%;bottom:88px}.laptop:after{width:235px}.mug{right:8%;width:75px;height:92px;font-size:16px}.possibility{font-size:21px;right:5%}}
      `}</style>

      <div className="demo">UNOFFICIAL REDESIGN CONCEPT — NOT THE OFFICIAL HOBO WEBSITE</div>
      <header className="siteHeader"><div className="nav shell"><a className="brand" href="#home"><span className="brandMark"><span></span></span><span className="brandText"><b>HOBO</b><small>COMPUTER SERVICES</small></span></a><nav className="desktopNav"><a href="#home">Home</a><a href="#services">Services</a><a href="#business">For Business</a><a href="#about">About</a><a href="#contact">Contact</a></nav><div className="navActions"><a className="phoneLink" href="tel:+14165613204">416 561-3204</a><a className="navCta" href="#contact">Request Support</a><details className="mobileMenu"><summary>☰</summary><div className="mobileMenuPanel"><a href="#home">Home</a><a href="#services">Services</a><a href="#business">For Business</a><a href="#about">About</a><a href="#contact">Contact</a></div></details></div></div></header>

      <section id="home" className="hero"><div className="heroGlow heroGlowOne"></div><div className="heroGlow heroGlowTwo"></div><div className="shell heroGrid"><div><p className="eyebrow">MARKHAM • TORONTO • GTA</p><h1>Reliable IT support for your <span>home & business.</span></h1><p className="lead">Fast, friendly help for computer repair, networking, setup and everyday technology problems.</p><div className="actions"><a className="primary" href="#contact">Request Support <span>→</span></a><a className="secondary" href="tel:+14165613204">Call 416 561-3204</a></div><div className="trustRow"><span><b>✓</b> Personalized service</span><span><b>✓</b> On-site support</span><span><b>✓</b> Local GTA service</span></div></div><div className="heroVisual"><div className="visualCard"><div className="visualTop"><span></span><span></span><span></span></div><div className="visualScreen"><div className="pulseRing"><div className="pulseCore">IT</div></div><div className="signal signalA"></div><div className="signal signalB"></div><div className="signal signalC"></div></div><div className="visualFooter"><span>Computer</span><span>Network</span><span>Support</span></div></div><div className="floatingBadge badgeOne"><strong>LOCAL</strong><small>Markham & GTA</small></div><div className="floatingBadge badgeTwo"><strong>SUPPORT</strong><small>Home & Business</small></div></div></div></section>

      <section className="proofBar"><div className="shell proofGrid"><span>Computer & Laptop Support</span><span>Wi-Fi & Networking</span><span>Virus & Spyware Removal</span><span>Home & Business</span></div></section>

      <section id="services" className="section shell servicesSection"><div className="sectionHead splitHead"><div><p className="eyebrow dark">WHAT WE DO</p><h2>Complete computer support, without the complexity.</h2></div><p>From a slow laptop to office networking, HOBO provides practical technology help for the systems you rely on every day.</p></div><div className="cards">{services.map(([num, icon, title, desc]) => <article className="card" key={title}><div className="cardTop"><div className="serviceMeta"><span className="serviceIcon"><ServiceIcon type={icon}/></span><span className="cardNum">{num}</span></div><span className="cardArrow">↗</span></div><h3>{title}</h3><p>{desc}</p><a href="#contact">Get support <span>→</span></a></article>)}</div></section>

      <section id="business" className="businessSection"><div className="shell businessGrid"><div className="businessVisual"><div className="dashboardWindow"><div className="dashboardHeader"><b>HOBO</b><span>System support</span></div><div className="dashboardBody"><div className="dashboardSide"><i></i><i></i><i></i><i></i></div><div className="dashboardMain"><div className="statusCard"><small>NETWORK</small><strong>Connected</strong><span className="statusLine"><i></i></span></div><div className="miniGrid"><div><small>DEVICES</small><b>Ready</b></div><div><small>SUPPORT</small><b>Local</b></div></div><div className="activity"><span></span><span></span><span></span><span></span><span></span></div></div></div></div></div><div className="businessCopy"><p className="eyebrow">FOR HOME OFFICES & SMALL BUSINESS</p><h2>Technology should help you work — not slow you down.</h2><p>HOBO supports the computers, wireless networks, printers and everyday systems that keep small businesses and home-based professionals moving.</p><div className="businessList"><span>✓ New workstation setup</span><span>✓ Network & Wi-Fi troubleshooting</span><span>✓ Printer and device connectivity</span><span>✓ Computer support & repair</span></div><a className="textLink" href="#contact">Talk about your setup →</a></div></div></section>

      <section id="about" className="section whySection"><div className="shell"><div className="sectionHead centered"><p className="eyebrow dark">WHY HOBO</p><h2>Local support. Clear answers. Practical help.</h2><p>Technology support built around real needs, not unnecessary complexity.</p></div><div className="whyGrid">{benefits.map(([icon,title,desc],index)=><article key={title}><div className="benefitTop"><span className="benefitIcon"><BenefitIcon type={icon}/></span><span className="benefitNum">0{index+1}</span></div><h3>{title}</h3><p>{desc}</p></article>)}</div></div></section>

      <section className="experimentalWhy" aria-label="Experimental Why Choose HOBO section"><div className="testWrap"><div className="testLeft"><div className="testLabel">EXPERIMENTAL SECTION</div><h2>Why Choose HOBO?</h2><p className="testSub">We’re more than just computer support. We’re your local IT partner.</p><div className="testBenefits"><div className="testBenefit"><div className="testBenefitIcon"><TestWhyIcon type="experienced"/></div><h3>Experienced</h3><p>Years of hands-on experience with home and business IT.</p></div><div className="testBenefit"><div className="testBenefitIcon"><TestWhyIcon type="friendly"/></div><h3>Friendly & Personal</h3><p>We explain things in plain English.</p></div><div className="testBenefit"><div className="testBenefitIcon"><TestWhyIcon type="fast"/></div><h3>Fast & Reliable</h3><p>Quick response and efficient service.</p></div><div className="testBenefit"><div className="testBenefitIcon"><TestWhyIcon type="location"/></div><h3>Local to Markham</h3><p>Proudly serving Markham and the Greater Toronto Area.</p></div></div></div><div className="testVisual"><div className="possibility">Small Business<br/>Big Possibilities</div><div className="plant"></div><div className="laptop"><div className="laptopScreen"><span></span><span></span><span></span><span></span></div></div><div className="mug">Good<br/>Tech<br/>Better<br/>Days</div><div className="desk"></div></div></div></section>

      <section className="processSection"><div className="shell processGrid"><div><p className="eyebrow">SIMPLE PROCESS</p><h2>Support in three straightforward steps.</h2></div><div className="steps"><div><span>01</span><div><b>Contact HOBO</b><p>Call or send a support request.</p></div></div><div><span>02</span><div><b>Explain the issue</b><p>Tell us what is happening and what you need.</p></div></div><div><span>03</span><div><b>Get practical support</b><p>Get help for your computer, network or setup.</p></div></div></div></div></section>

      <section id="contact" className="contactSection"><div className="shell contactGrid"><div className="contactCopy"><p className="eyebrow">LET'S SOLVE THE PROBLEM</p><h2>Need computer help?</h2><p>HOBO Computer Services is located in Markham and serves Toronto and the GTA.</p><div className="contactDetails"><a href="tel:+14165613204"><small>PHONE</small><strong>416 561-3204</strong></a><a href="mailto:info@hobocomputerservices.com"><small>EMAIL</small><strong>info@hobocomputerservices.com</strong></a></div></div><form action="mailto:info@hobocomputerservices.com" method="post" encType="text/plain"><div className="formHead"><span>REQUEST SUPPORT</span><small>Tell us how we can help.</small></div><div className="formRow"><input name="name" placeholder="Full name" required/><input name="email" type="email" placeholder="Email address" required/></div><div className="formRow"><input name="phone" placeholder="Phone number"/><select name="service" defaultValue=""><option value="" disabled>Select a service</option><option>Computer Repair</option><option>Business IT Support</option><option>Wi-Fi & Networking</option><option>Virus Removal</option><option>Computer Setup</option><option>Web Services</option></select></div><textarea name="message" placeholder="How can we help?" rows="5"/><button type="submit">Send Request <span>→</span></button><small className="formNote">Demo form: opens your email application. A production version would use a secure form backend.</small></form></div></section>

      <footer><div className="shell footerMain"><div className="brand inverse"><span className="brandMark"><span></span></span><span className="brandText"><b>HOBO</b><small>COMPUTER SERVICES</small></span></div><div className="footerLinks"><a href="#services">Services</a><a href="#business">For Business</a><a href="#about">About</a><a href="#contact">Contact</a></div></div><div className="shell footerBottom"><p>Unofficial redesign concept created for demonstration purposes.</p><p>Markham • Toronto • GTA</p></div></footer>
    </main>
  );
}
